apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: seconddepl
  name: seconddepl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seconddepl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seconddepl
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
